### ISSUE TITLE
Question about proxies

### ISSUE THREAD

**Issue by alexellis** [fgksgf/GitHub-Trending-Crawler#4]
This utility looks good. I think it would make a good function for OpenFaaS or faasd. 

Why is a random pool of proxies required? The code appears to read html pages which are not usually rate limited?

**Comment by fgksgf** [comment]
@alexellis Thanks, that sounds great. 

You are right. Actually, the proxy pool is not required, and the proxy is not used by default, which is just in case :) 

I would consider if remove the proxy feature.
